{{- if .Values.kafkaTrigger.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    kubeless: kafka-trigger-controller
  name: kafka-trigger-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      kubeless: kafka-trigger-controller
  template:
    metadata:
      labels:
        kubeless: kafka-trigger-controller
    spec:
      containers:
      - image: "{{ .Values.kafkaTrigger.deployment.image.repository }}:{{ .Values.kafkaTrigger.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.kafkaTrigger.deployment.image.pullPolicy }}
        name: kafka-trigger-controller
        env:
        - name: KAFKA_BROKERS
          value: {{ .Values.kafkaTrigger.env.kafkaBrokers }}
        - name: KAFKA_ENABLE_TLS
          value: "true"
        - name: KAFKA_ENABLE_SASL
          value: "true"
        - name: KAFKA_USERNAME
          value: {{ .Values.kafkaTrigger.env.username }}
        - name: KAFKA_PASSWORD
          value: {{ .Values.kafkaTrigger.env.password }}
        - name: KAFKA_INSECURE
          value: "true"
        - name: KUBELESS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBELESS_CONFIG
          value: kubeless-config
        - name: KUBELESS_LOG_LEVEL
          value: DEBUG
      serviceAccountName: controller-acct
{{- end }}
